algoritmo "Somar 2 números inteiros"


var

 // declaração de variáveis
 
     A : inteiro
     B, C : inteiro

inicio

// comando de entrada de dados

     escreva("O número é: ")
     leia (A)
     
     escreva("O número é: ")
     leia (B)
     
     escreva("O número é: ")
     leia (C)
     
// processamento dos dados

     C <- A + B

// saída de dados

     escreva(C)


fimalgoritmo